services:
  sonarqube:
    image: ${SONARQUBE_IMAGE:-sonarqube:lts-community}
    container_name: ${SONARQUBE_CONTAINER_NAME:-sonarqube}
    labels:
      com.example.description: "SonarQube service"
      com.example.environment: "${ENVIRONMENT:-production}"
      com.example.version: "${VERSION:-1.0}"
    environment:
      - SONAR_JDBC_URL=${SONAR_JDBC_URL:-jdbc:postgresql://sonar_db:5432/sonar}
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME:-sonar}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD:-sonar}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    ports:
      - "${SONAR_PORT:-9000}:9000"
    networks:
      - sonarnet
      - public-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    depends_on:
      sonar_db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  sonar_db:
    image: ${SONAR_DB_IMAGE:-postgres:13}
    container_name: ${SONAR_DB_CONTAINER_NAME:-sonar_db}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sonar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sonar}
      - POSTGRES_DB=${POSTGRES_DB:-sonar}
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonarnet
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sonar} -d ${POSTGRES_DB:-sonar}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

networks:
  sonarnet:
    driver: bridge
    internal: true
  public-network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db_data:
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/backup