services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE:-rabbitmq:3.12-management}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-password}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"      # AMQP port
      - "${RABBITMQ_MGMT_PORT:-15672}:15672" # Management UI
      - "${RABBITMQ_PROMETHEUS_PORT:-15692}:15692" # Prometheus metrics
    networks:
      - rabbitmq_network
      - public_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  rabbitmq-exporter:
    image: ${RABBITMQ_EXPORTER_IMAGE:-kbudde/rabbitmq-exporter:latest}
    container_name: ${RABBITMQ_EXPORTER_CONTAINER_NAME:-rabbitmq-exporter}
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=${RABBITMQ_USER:-admin}
      - RABBIT_PASSWORD=${RABBITMQ_PASSWORD:-password}
      - PUBLISH_PORT=9419
      - OUTPUT_FORMAT=TTY
      - LOG_LEVEL=info
    ports:
      - "${RABBITMQ_EXPORTER_PORT:-9419}:9419"
    networks:
      - rabbitmq_network
      - public_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9419/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

networks:
  rabbitmq_network:
    driver: bridge
    internal: true
  public_network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local
