services:
  minio:
    image: ${MINIO_IMAGE:-minio/minio:latest}
    container_name: ${MINIO_CONTAINER_NAME:-minio}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-http://localhost:9001}
    volumes:
      - minio_data:/data
      - ./config:/root/.minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"      # S3 API
      - "${MINIO_CONSOLE_PORT:-9001}:9001"   # Web Console
    networks:
      - minio_network
      - public_network
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  minio-client:
    image: ${MINIO_CLIENT_IMAGE:-minio/mc:latest}
    container_name: ${MINIO_CLIENT_CONTAINER_NAME:-minio-client}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - ./scripts:/scripts:ro
      - ./data:/data
    networks:
      - minio_network
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/uploads --ignore-existing;
      /usr/bin/mc mb myminio/backups --ignore-existing;
      /usr/bin/mc mb myminio/documents --ignore-existing;
      /usr/bin/mc policy set public myminio/uploads;
      /usr/bin/mc policy set private myminio/backups;
      /usr/bin/mc policy set private myminio/documents;
      exit 0;
      "
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: "no"
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

networks:
  minio_network:
    driver: bridge
    internal: true
  public_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
